title: Samenvattingen ICT & Elektronica
description: Samenvattingen, labo's en opdrachten uit mijn opleiding ICT & Elektronica
theme: minima
lang: nl

exclude:
  - CLAUDE.md
  - README.md
  - "*.tex"
